#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🔨 Building ESM version...');

// Project root (parent of scripts/)
const projectRoot = path.join(__dirname, '..');

// Source file location
const sourceFile = path.join(projectRoot, 'src', 'RegXpChef.js');

// Output directory
const distDir = path.join(projectRoot, 'dist');

// Check if source exists
if (!fs.existsSync(sourceFile)) {
  console.error(`❌ Source file not found: ${sourceFile}`);
  console.error('\nExpected project structure:');
  console.error('  regxpchef/');
  console.error('    ├── src/');
  console.error('    │   └── RegXpChef.js  ← Source file');
  console.error('    └── scripts/');
  console.error('        └── build-esm.js  ← This file');
  process.exit(1);
}

// Create dist directory if it doesn't exist
if (!fs.existsSync(distDir)) {
  console.log(`📁 Creating dist/ directory...`);
  fs.mkdirSync(distDir, { recursive: true });
}

// Read source file
let code = fs.readFileSync(sourceFile, 'utf8');

// Store original for CommonJS output
const originalCode = code;

// Remove CommonJS exports for ESM version
code = code.replace(
  /if \(typeof module !== 'undefined' && module\.exports\) \{[\s\S]*?\}/g,
  ''
);

// Remove browser global assignment
code = code.replace(
  /if \(typeof window !== 'undefined'\) \{[\s\S]*?\}/g,
  ''
);

// Trim trailing whitespace
code = code.trim();

// Add ESM exports
const esmExports = `

// ES6 Module Exports (auto-generated by build-esm.js)
export default RegXpChef;

// Named exports for tree-shaking
export const compile = (...args) => RegXpChef.compile(...args);
export const assemble = (...args) => RegXpChef.assemble(...args);
export const escape = (source) => RegXpChef.escape(source);
export const groupCounts = (source) => RegXpChef.groupCounts(source);
export const matchGroups = (match) => RegXpChef.matchGroups(match);
`;

code += esmExports;

// Write ESM file
const esmOutputFile = path.join(distDir, 'RegXpChef.mjs');
fs.writeFileSync(esmOutputFile, code, 'utf8');
console.log(`✅ Created: dist/RegXpChef.mjs`);

// Remove all module system checks
code = originalCode
  .replace(/if \(typeof module !== 'undefined' && module\.exports\) \{[\s\S]*?\}/g, '')
  .replace(/if \(typeof window !== 'undefined'\) \{[\s\S]*?\}/g, '')
  .trim();

// ============================================================
// 1. Browser ESM (.mjs)
// ============================================================
const browserESM = code + `

// Browser ESM Exports
export default RegXpChef;
export const compile = (...args) => RegXpChef.compile(...args);
export const assemble = (...args) => RegXpChef.assemble(...args);
export const escape = (source) => RegXpChef.escape(source);
export const groupCounts = (source) => RegXpChef.groupCounts(source);
export const matchGroups = (match) => RegXpChef.matchGroups(match);
`;

fs.writeFileSync(
  path.join(distDir, 'RegXpChef.browser.mjs'),
  browserESM,
  'utf8'
);
console.log('✅ Created: dist/RegXpChef.browser.mjs (ESM for browsers)');

// ============================================================
// 2. UMD Build
// ============================================================
const umdWrapper = `/**
 * RegXpChef - UMD Build
 * Universal Module Definition - works everywhere
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.RegXpChef = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

${code}

  return RegXpChef;
}));
`;

fs.writeFileSync(
  path.join(distDir, 'RegXpChef.umd.js'),
  umdWrapper,
  'utf8'
);
console.log('✅ Created: dist/RegXpChef.umd.js (UMD)');

// ============================================================
// 3. IIFE (Browser global)
// ============================================================
const iifeWrapper = `/**
 * RegXpChef - Browser IIFE Build
 * Exposes: window.RegXpChef
 */
var RegXpChef = (function() {
  'use strict';

${code}

  return RegXpChef;
})();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = RegXpChef;
}
`;

fs.writeFileSync(
  path.join(distDir, 'RegXpChef.browser.js'),
  iifeWrapper,
  'utf8'
);
console.log('✅ Created: dist/RegXpChef.browser.js (IIFE)');

// ============================================================
// 4. Report sizes
// ============================================================
console.log('\n📦 File sizes:');
['RegXpChef.browser.mjs', 'RegXpChef.umd.js', 'RegXpChef.browser.js'].forEach(file => {
  const filePath = path.join(distDir, file);
  const size = fs.statSync(filePath).size;
  console.log(`   ${file.padEnd(25)} ${(size / 1024).toFixed(2)} KB`);
});

console.log('\n🎉 Browser builds complete!');

// Copy original to dist as CommonJS version
const cjsOutputFile = path.join(distDir, 'RegXpChef.js');
fs.writeFileSync(cjsOutputFile, originalCode, 'utf8');
console.log(`✅ Created: dist/RegXpChef.js`);

// Copy TypeScript definitions if they exist
const srcDts = path.join(projectRoot, 'src', 'RegXpChef.d.ts');
const rootDts = path.join(projectRoot, 'RegXpChef.d.ts');
const distDts = path.join(distDir, 'RegXpChef.d.ts');

if (fs.existsSync(srcDts)) {
  fs.copyFileSync(srcDts, distDts);
  console.log(`✅ Copied: dist/RegXpChef.d.ts (from src/)`);
} else if (fs.existsSync(rootDts)) {
  fs.copyFileSync(rootDts, distDts);
  console.log(`✅ Copied: dist/RegXpChef.d.ts (from root)`);
} else {
  console.log(`⚠️  No TypeScript definitions found (optional)`);
}

// Validate by attempting to load both versions
async function validate() {
  console.log('\n🧪 Validating builds...');
  
  // Test CommonJS
  try {
    const RegXpChefCJS = require(cjsOutputFile);
    const testResult = RegXpChefCJS.escape('test');
    if (testResult === 'test') {
      console.log('✅ CommonJS validation passed');
    } else {
      throw new Error(`Unexpected result: ${testResult}`);
    }
  } catch (error) {
    console.error('❌ CommonJS validation failed:', error.message);
    process.exit(1);
  }
  
  // Test ESM (Node.js 14+ supports dynamic import)
  try {
    // Use dynamic import to load ESM
    const moduleURL = new URL('file://' + esmOutputFile.replace(/\\/g, '/'));
    const RegXpChefESM = await import(moduleURL.href);
    
    if (!RegXpChefESM.default) {
      throw new Error('No default export found');
    }
    
    const testResult = RegXpChefESM.default.escape('test');
    if (testResult === 'test') {
      console.log('✅ ESM default export validation passed');
    } else {
      throw new Error(`Unexpected result: ${testResult}`);
    }
    
    // Test named export
    if (typeof RegXpChefESM.escape === 'function') {
      const namedResult = RegXpChefESM.escape('test');
      if (namedResult === 'test') {
        console.log('✅ ESM named exports validation passed');
      }
    } else {
      throw new Error('Named export "escape" not found');
    }
    
  } catch (error) {
    console.error('❌ ESM validation failed:', error.message);
    process.exit(1);
  }
}

// Run validation
validate().then(() => {
  // Report file sizes
  const sourceSize = fs.statSync(sourceFile).size;
  const esmSize = fs.statSync(esmOutputFile).size;
  const cjsSize = fs.statSync(cjsOutputFile).size;

  console.log('\n📦 File sizes:');
  console.log(`   Source:   ${(sourceSize / 1024).toFixed(2)} KB`);
  console.log(`   ESM:      ${(esmSize / 1024).toFixed(2)} KB`);
  console.log(`   CommonJS: ${(cjsSize / 1024).toFixed(2)} KB`);

  console.log('\n🎉 Build complete!');
}).catch(error => {
  console.error('\n❌ Build failed:', error);
  process.exit(1);
});